#CRIE UM PACOTE CHAMADO utilidadesCeV QUE TENHA DOIS MÓDULOS INTERNOS CHAMADOS MOEDA E DADO.
#TRANSFIRA TODAS AS FUNÇÕES UTILIZADAS NOS DESAFIOS 107,108,109,110 PARA O PRIMEIRO PACOTE E MANTENHA TUDO FUNCIONANDO

from utilidadesCeV import moeda

p=float(input('Digite o preço: R$'))
moeda.resumo(p,80,35)