#DENTRO DO PACOTE utilidadesCeV QUE CRIAMOS NO DESAFIO 111, TEMOS UM MÓDULO CHAMADO DADO. CRIE UMA FUNÇÃO CHAMADA leiaDinheiro() QUE SEJA CAPAZ DE FUNCIONAR COMO A FUNÇÃO INPUT MAS COM UMA VALIDAÇÃO DE DADOS PARA ACEITAR APENAS VALORES QUE SEJAM MONETÁRIOS - ACEITAR VIRGULAS 99,99, PONTO 99.99 E DAR ERRO PARA VAZIO E STRINGS

from utilidadesCeV import dado,moeda

moeda.resumo(dado.leiaDinheiro('Digite o preço: R$'),80,35) 